apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: web
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: web
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: web
    spec:
      containers:
      - args:
        - gunicorn
        - -b
        - 0.0.0.0:8080
        - liveontwitch.wsgi:application
        - --env
        - DJANGO_SETTINGS_MODULE=liveontwitch.prod
        - --log-level
        - info
        - --reload
        env:
        - name: DB_HOST
          value: db
        - name: DB_NAME
          value: postgres
        - name: DB_PASS
          value: postgres
        - name: DB_USER
          value: postgres
        image: gdmurray/liveontwitch:$COMMIT_SHA1
        name: web
        ports:
        - containerPort: 8080
        resources: {}
        volumeMounts:
        - mountPath: /code
          name: web-claim0
      restartPolicy: Always
      volumes:
      - name: web-claim0
        persistentVolumeClaim:
          claimName: web-claim0
status: {}
