# Generated by Django 2.2 on 2019-04-12 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.OAUTH2_PROVIDER_ACCESS_TOKEN_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verifier',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.CreateModel(
            name='TemporaryToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=256)),
                ('approved', models.BooleanField(default=False)),
                ('error_message', models.CharField(max_length=300, null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('token', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.OAUTH2_PROVIDER_ACCESS_TOKEN_MODEL)),
            ],
        ),
    ]
