# Generated by Django 2.2 on 2019-04-13 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_temporarytoken_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporarytoken',
            name='provider',
            field=models.IntegerField(choices=[(0, 'Twitch'), (1, 'Twitter')], default=0),
        ),
    ]
