# Generated by Django 2.2 on 2019-04-13 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_temporarytoken_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporarytoken',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
