# Generated by Django 2.2 on 2019-04-11 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OAuth2AccessToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField(help_text='access token (OAuth2)', verbose_name='token')),
                ('token_secret', models.TextField(blank=True, help_text='refresh token (OAuth2)', verbose_name='token secret')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='expires at')),
            ],
            options={
                'verbose_name': 'oauth2 application token',
                'verbose_name_plural': 'oauth2 application tokens',
            },
        ),
        migrations.CreateModel(
            name='TwitterAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=140, null=True)),
                ('uid', models.CharField(max_length=60, null=True)),
            ],
            options={
                'verbose_name': 'twitter account',
                'verbose_name_plural': 'twitter accounts',
            },
        ),
    ]
