# Generated by Django 2.2 on 2019-04-12 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Twitter', '0002_auto_20190411_2104'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oauth2accesstoken',
            options={'verbose_name': 'Twitter oauth2 token', 'verbose_name_plural': 'Twitter oauth2 tokens'},
        ),
    ]
