# Generated by Django 2.2 on 2019-04-13 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Twitter', '0003_auto_20190412_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='oauth2accesstoken',
            name='request_token',
            field=models.TextField(null=True),
        ),
    ]
