# Generated by Django 2.2 on 2019-04-13 04:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Twitter', '0004_oauth2accesstoken_request_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oauth2accesstoken',
            name='request_token',
        ),
        migrations.CreateModel(
            name='TwitterTemporaryToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_token', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
