# Generated by Django 2.2 on 2019-04-13 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Twitter', '0005_auto_20190413_0446'),
    ]

    operations = [
        migrations.AddField(
            model_name='twittertemporarytoken',
            name='oauth_token',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
