# Generated by Django 2.2 on 2019-04-24 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Twitter', '0006_twittertemporarytoken_oauth_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitteraccount',
            name='name',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='twitteraccount',
            name='profile_image_url_https',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='twitteraccount',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='twitteraccount',
            name='verified',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='oauth2accesstoken',
            name='account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Twitter.TwitterAccount'),
        ),
    ]
