# Generated by Django 2.2 on 2019-04-24 22:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Twitter', '0007_auto_20190424_2101'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('update_status_active', models.BooleanField(default=False)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Twitter.TwitterAccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuration', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UsernameConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('live_text', models.TextField(max_length=30, null=True)),
                ('positioning', models.CharField(choices=[('BEFORE', 'Before'), ('AFTER', 'After')], default='BEFORE', max_length=10)),
                ('active', models.BooleanField(default=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('config', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Twitter.LiveConfiguration')),
            ],
        ),
        migrations.CreateModel(
            name='BioConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('live_text', models.TextField(max_length=30, null=True)),
                ('positioning', models.CharField(choices=[('BEFORE', 'Before'), ('AFTER', 'After')], default='BEFORE', max_length=10)),
                ('active', models.BooleanField(default=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('config', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Twitter.LiveConfiguration')),
            ],
        ),
    ]
