# Generated by Django 2.2 on 2019-04-25 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Twitter', '0008_bioconfiguration_liveconfiguration_usernameconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitteraccount',
            name='description',
            field=models.TextField(blank=True, max_length=600, null=True),
        ),
    ]
