# Generated by Django 2.2 on 2019-04-26 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Twitter', '0010_auto_20190426_0516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitteraccount',
            name='modified_bio',
            field=models.TextField(blank=True, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='twitteraccount',
            name='modified_name',
            field=models.TextField(blank=True, max_length=140, null=True),
        ),
    ]
