# Generated by Django 2.2 on 2019-04-12 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitch', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oauth2accesstoken',
            options={'verbose_name': 'Twitch oauth2 token', 'verbose_name_plural': 'Twitch oauth2 tokens'},
        ),
    ]
