# Generated by Django 2.2 on 2019-04-14 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitch', '0003_remove_twitchaccount_is_streaming'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwitchSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('subscription_date', models.DateTimeField(null=True)),
                ('expiry', models.DateTimeField(null=True)),
                ('expiry_seconds', models.IntegerField(default=864000)),
                ('confirmed', models.BooleanField(default=False)),
                ('account', models.OneToOneField(on_delete=models.Model, to='twitch.TwitchAccount')),
            ],
        ),
    ]
