# Generated by Django 2.2 on 2019-04-24 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitch', '0004_twitchsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitchsubscription',
            name='error_message',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
