# Generated by Django 2.2 on 2019-04-24 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitch', '0005_twitchsubscription_error_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitchaccount',
            name='email',
            field=models.CharField(max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='twitchaccount',
            name='logo',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='twitchaccount',
            name='partnered',
            field=models.BooleanField(default=False),
        ),
    ]
