# Generated by Django 2.2 on 2019-04-25 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitch', '0006_auto_20190424_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitchsubscription',
            name='error_message',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
