# Generated by Django 2.2 on 2019-04-25 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twitch', '0007_auto_20190425_0440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oauth2accesstoken',
            name='account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='twitch.TwitchAccount'),
        ),
        migrations.AlterField(
            model_name='twitchsubscription',
            name='account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='twitch.TwitchAccount'),
        ),
        migrations.CreateModel(
            name='TwitchEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline')], max_length=15)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='twitch.TwitchSubscription')),
            ],
        ),
    ]
