# Generated by Django 2.2 on 2019-04-25 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitch', '0008_auto_20190425_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='oauth2accesstoken',
            name='application_token',
            field=models.BooleanField(default=False),
        ),
    ]
