# Generated by Django 2.2 on 2019-04-25 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twitch', '0009_oauth2accesstoken_application_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oauth2accesstoken',
            name='account',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='twitch.TwitchAccount'),
        ),
    ]
