# Generated by Django 2.2 on 2019-04-25 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitch', '0010_auto_20190425_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oauth2accesstoken',
            name='token_secret',
            field=models.TextField(blank=True, help_text='refresh token (OAuth2)', null=True, verbose_name='token secret'),
        ),
    ]
