# Generated by Django 2.2 on 2019-04-25 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitch', '0011_auto_20190425_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitchsubscription',
            name='verifier',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
