# Generated by Django 2.2 on 2019-04-25 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twitch', '0012_twitchsubscription_verifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitchevent',
            name='subscription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='twitch.TwitchSubscription'),
        ),
        migrations.AlterField(
            model_name='twitchevent',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='twitch.TwitchAccount'),
        ),
    ]
