# Generated by Django 2.2 on 2019-04-25 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitch', '0013_auto_20190425_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitchevent',
            name='event_id',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
