apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: postgres
data:
  POSTGRES_DB: liveontwitchdb
  POSTGRES_USER: greg
  POSTGRES_PASSWORD: uG9Gn6TQdSBbv9FOJETFnICbdCKlp57f