apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: django
  labels:
    app: django
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: django
  template:
    metadata:
      labels:
        pod: django
    spec:
      initContainers:
        - name: migrate
          image: gdmurray/liveontwitch:$COMMIT_SHA1
          imagePullPolicy: IfNotPresent
          command: ["python", "manage.py", "migrate"]
          envFrom:
            - configMapRef:
                name: django-config
      containers:
        - name: django
          command: ['gunicorn','-b','0.0.0.0:8080','liveontwitch.wsgi:application','--env','DJANGO_SETTINGS_MODULE=liveontwitch.prod','--log-level','info','--reload']
          image: gdmurray/liveontwitch:$COMMIT_SHA1
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: django-config