apiVersion: batch/v1
kind: Job
metadata:
  name: django-migrations
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
      - name: django
        image: gdmurray/liveontwitch:$COMMIT_HASH
        command: ["python", "manage.py", "migrate"]
      restartPolicy: Never
      imagePullPolicy: Always
  backoffLimit: 4