apiVersion: batch/v1
kind: Job
metadata:
  name: django-migrations
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
      - name: django
        image: gdmurray/liveontwitch:$COMMIT_SHA1
        command: ["python", "manage.py", "migrate"]
      restartPolicy: Never
  backoffLimit: 4